# Completa el TODO, y luego: oc apply -f manifests/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: podpet-config
  labels:
    app: podpet
    lab: lab03
data:
  # TODO: define un nombre para la mascota, por ejemplo "Configstein"
  PET_NAME: ""
